
# Site settings
title: Tian Yu
name: Tian Yu
subtitle:  
email: yu_tian@bupt.edu.cn
description: >
   Student
baseurl: ""
url: "https://seventianyu.github.io/"
github_username:  seventianyu
disqus_baseurl: "https://seventianyu.github.io/"
disqus_shortname: https-seventianyu-github-io
permalink: :title
google-site-verification: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tian Yu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: github.com
    url: https://github.com/SevenTianyu
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Tian Yu
    url: https://www.linkedin.cn/in/yu-tian-425a15197
    desc: Connect with me on LinkedIn
    share: true
